id: ICCC2A0B3
legacy_id: P009198
ocr_import_info:
  bdrc_scan_id: W1AC31
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:46:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T16:58:01.316006+00:00'
last_modified: 2022-08-31 00:59:35.124784
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC31
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC31
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོ་རྩ་བའི་མཆན་འགྲེལ།༼གཞི་སྟོད༽༼གཞི་སྨད༽
  author: མཚོ་སྣ་བ་ཤེས་རབ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7254896867673121
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I2PD18125:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18125
      total_pages: 424
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18125.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.6694322469653886
    legacy_id: v001
  I2PD18126:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18126
      total_pages: 384
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD18126.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8186478451319446
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
